### ISSUE TITLE
Dateien bei jedem Aufruf neu erstellen

### ISSUE THREAD

**Issue by der-phillip** [kaystrobach/TYPO3.dyncss_less#10]
Hallo,

da meine Less-Datei viele weiter Dateien inkludiert und diese wiederum einige Dateien, muss ich jedes mal die Datei ohne Änderung speichern damit das CSS neue erstellt wird.

Kann man einstellen, dass in der Entwicklung die Dateien jedes Mal neu erstellt werden?

**Comment by kaystrobach** [comment]
preset = development im installtool

oder 

application context = development

**Comment by kaystrobach** [comment]
btw: https://github.com/kaystrobach/TYPO3.dyncss#caching :smile:
