### ISSUE TITLE
Hi, does dyncss works with TYPO3 > 7.0.99

### ISSUE THREAD

**Issue by metaxos** [kaystrobach/TYPO3.dyncss_less#13]
Hi

I wanted to install dyncss_less, which uses dyncss. dyncss is set to TYPO3 (6.2.10 - 7.0.99).
Can I use both with Typo3 7.6.?

Regards

**Comment by kaystrobach** [comment]
Take a look into git master please

----- Originale Nachricht -----
Von: metaxos <notifications@github.com>
Gesendet: 27.11.2015 - 09:27
An: "kaystrobach/TYPO3.dyncss_less" <TYPO3.dyncss_less@noreply.github.com>
Betreff: [TYPO3.dyncss_less] Hi, does dyncss works with TYPO3 > 7.0.99 (#13)

**Comment by metaxos** [comment]
Hi

I mean dyncss (https://github.com/kaystrobach/TYPO3.dyncss/blob/master/ext_emconf.php)

**Comment by kaystrobach** [comment]
Then i missed to push it ;) i raised the Version yesterday atleast locally

----- Originale Nachricht -----
Von: metaxos <notifications@github.com>
Gesendet: 27.11.2015 - 11:08
An: "kaystrobach/TYPO3.dyncss_less" <TYPO3.dyncss_less@noreply.github.com>
Betreff: Re: [TYPO3.dyncss_less] Hi, does dyncss works with TYPO3 > 7.0.99 (#13)

**Comment by kaystrobach** [comment]
see no problem with latest master
