### ISSUE TITLE
Fatal error: Cannot call constructor

### ISSUE THREAD

**Issue by larp-welt** [kaystrobach/TYPO3.dyncss_less#14]
Hello!

I'm getting this Error, if using Version >= 0.7.3:

`Fatal error: Cannot call constructor in /home/www/my_dir/typo3conf/ext/dyncss_less/Classes/Parser/LessParser.php on line 18`

After reverting back to 0.7.2, all works fine again!

Im using Typo3 7.5.0.

I allready tried to clear all caches...

**Comment by kaystrobach** [comment]
which php version are you using?

**Comment by kaystrobach** [comment]
and have you tried updating to dyncss 0.7.4 atleast, better 0.7.5?

**Comment by larp-welt** [comment]
Hello!

My Typo3 didn't show any update of dyncss.

After manually updating, all things work fine!

Thank you very much!

**Comment by kaystrobach** [comment]
Will recheck TER ;)

----- Originale Nachricht -----
Von: larp-welt <notifications@github.com>
Gesendet: 29.11.2015 - 15:12
An: "kaystrobach/TYPO3.dyncss_less" <TYPO3.dyncss_less@noreply.github.com>
Betreff: Re: [TYPO3.dyncss_less] Fatal error: Cannot call constructor (#14)
