### ISSUE TITLE
Typo3 7.6

### ISSUE THREAD

**Issue by der-phillip** [kaystrobach/TYPO3.dyncss_less#15]
Hallo, nach dem Update auf die aktuelle TYPO3 Version 7.6.0 erhalte ich diesen Fehler.

Fatal error: Class 'KayStrobach\Dyncss\Configuration\BeRegistry' not found in typo3/typo3conf/ext/dyncss_less/ext_localconf.php on line 3

**Comment by kaystrobach** [comment]
Kannst du bitte vob dyncss und dyncss_less die jeweiligen git mast probieren? Danke

----- Originale Nachricht -----
Von: Phillip <notifications@github.com>
Gesendet: 03.12.2015 - 15:31
An: "kaystrobach/TYPO3.dyncss_less" <TYPO3.dyncss_less@noreply.github.com>
Betreff: [TYPO3.dyncss_less] Typo3 7.6 (#15)

**Comment by der-phillip** [comment]
Funktioniert, bei https://github.com/kaystrobach/TYPO3.dyncss kommt allerdings eine Versionswarnung.

**Comment by kaystrobach** [comment]
An den Versionsnummern arbeiten wir am Wochenende ;)

**Comment by kfinke** [comment]
Hi, I got the same error. Updated dyncss and dyncss_less from github. Started with TYPO3 7.6.0, updated to 7.6.1. Deleted typo3temp-folder. Still the same error.

**Comment by kaystrobach** [comment]
@der-phillip do you use composer? or core autoloading?

**Comment by kaystrobach** [comment]
please recheck current release and reopen if still a problem
