### ISSUE TITLE
packagist.org

### ISSUE THREAD

**Issue by kersten** [kaystrobach/TYPO3.dyncss_less#21]
Hi @kaystrobach,

would be nice to see this package on https://packagist.org too, like the scss one.

Would you mind to set typo3 dependency to <8.8 in composer.json?

**Comment by kaystrobach** [comment]
https://packagist.org/packages/kaystrobach/dyncss-less

**Comment by kersten** [comment]
Hi, thanks but no typo3 < 8.8.

**Comment by kaystrobach** [comment]
fixed in master, but need to do a new release ...
