### ISSUE TITLE
LESS - Clear cache

### ISSUE THREAD

**Issue by tdeuling** [kaystrobach/TYPO3.dyncss_less#9]
Durch das '_compileFile return FALSE' wird nun das LESS nur noch kompiliert, wenn sich die Import-Datei ändert, nicht aber wenn sich Dateien aus den enthaltenen includes ändern.

Hier für muss eine Lösung gefunden werden.
Eine Möglichkeit wäre: Ein clear cache-Button für den Dyncss-Cache. Zusätzlich dazu sollte es dann vielleicht aber auch ein TS-Flag geben, um den Cache für die Entwicklungszeit komplett zu deaktivieren.

**Comment by kaystrobach** [comment]
den clear cache button gibt es ja, wenn das problem noch existiert, bitte neu öffnen
